assets:
    - kind: fund
      market: ""
      code: "011513"
    - kind: fund
      market: ""
      code: "012734"
    - kind: fund
      market: ""
      code: "011609"
    - kind: fund
      market: ""
      code: "012349"
    - kind: fund
      market: ""
      code: "001595"
    - kind: fund
      market: ""
      code: "016068"
    - kind: fund
      market: ""
      code: "024913"
    - kind: fund
      market: ""
      code: "562500"
    - kind: fund
      market: ""
      code: "018734"
    - kind: fund
      market: ""
      code: "013180"
    - kind: fund
      market: ""
      code: "017938"
    - kind: fund
      market: ""
      code: "015599"
    - kind: fund
      market: ""
      code: "023432"
    - kind: fund
      market: ""
      code: "018536"
    - kind: fund
      market: ""
      code: "012969"
    - kind: fund
      market: ""
      code: "004433"
    - kind: fund
      market: ""
      code: "004744"
    - kind: fund
      market: ""
      code: "008086"
    - kind: fund
      market: ""
      code: "014332"
    - kind: fund
      market: ""
      code: "007882"
    - kind: fund
      market: ""
      code: "020973"
    - kind: stock
      market: sh
      code: "688435"
settings:
    refresh_interval_sec: 90
    alert_cooldown_min: 30
    max_concurrent_requests: 5
    change_color_scheme: red_up_green_down
